Training:
  model_path: '/kaggle/working/YoloCornerFinetune/pretrained_model/yolov8s-pose.pt'   # Pre-trained model (n, s, m, l, x)
  epochs: 100
  img_size: 640
  batch_size: 16
  project: 'card_corner_detection'
  name: 'experiment_1'
  save_period: 10  # Save checkpoint every N epochs
  cache: true      # Cache images for faster training
  augment: true    # Enable data augmentation
  device: 0,1
  loss:
    kpt: 4.0
    bop: 3.0
  
Dataset:
  data_yaml_path:  '/kaggle/working/YoloCornerFinetune/data.yaml'

Augmentations:
  # Geometric augmentations
  mosaic: 0.0        # Mosaic augmentation probability
  mixup: 0.0         # Mixup augmentation probability
  degrees: 90        # Rotation range (-degrees to +degrees)
  translate: 0.1     # Translation fraction of image size
  scale: 0.5         # Scale range (1-scale to 1+scale)
  shear: 0.0         # Shear angle range
  perspective: 0.1 # Perspective transformation
  
  # Flip augmentations
  flipud: 0.0        # Vertical flip probability (disabled for cards)
  fliplr: 0.5        # Horizontal flip probability
  
  # Color augmentations
  hsv_h: 0.1         # Hue augmentation range
  hsv_s: 0.7         # Saturation augmentation range  
  hsv_v: 0.7         # Value (brightness) augmentation range